Fix downgrade builds

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -220,7 +220,7 @@ fi
 echo "Installing npm packages"
 if [ -e "$APP_SOURCE_DIR"/package.json ]; then
   echo "---> install   --legacy-peer-deps"
-  METEOR update --npm
+  METEOR update --npm || echo "-----> Warning: 'meteor update --npm' failed.  This is probably a downgrade build"
   NPM_CONFIG_PRODUCTION=false $METEOR_NPM install --legacy-peer-deps
 fi
 
